### ISSUE TITLE
关于如何使用Flare

### ISSUE THREAD

**Issue by zeroRains** [tsinghua-ideal/flare#2]
我根据README的描述搭建了Flare的环境（用的SGX_MOD=SIM的方式），我观察到README只描述到compile就结束了，请问应该如何使用Local的Flare呢？（纯小白）

**Comment by AmbitionXiang** [comment]
如果编译成功了，在bin下会有个binary，先`source set_env_local.sh` ，再运行该binary，默认会跑pearson correlation这个benchmark。另外我没有测试过SGX_MOD=SIM。

**Comment by zeroRains** [comment]
好的，谢谢~

**Comment by zeroRains** [comment]
Hello~，再次打扰一下，请问`app/benchmarks`的数据文件应该怎么获取呢？
![image](https://github.com/tsinghua-ideal/flare/assets/57100978/2fee8b4b-f67c-4b62-ac46-d9faa7cfb6f9)
