### ISSUE TITLE
关于各分支含义的问题

### ISSUE THREAD

**Issue by SunnyXia3579** [tsinghua-ideal/flare#4]
您好，Flare的README文档未指出各分支的具体含义，所以我想请教您几个问题

（1）master分支是encryption mode还是oblivious mode？
（2）oblivious_exp和oblivious_soda的区别是什么，以及谁的性能更好？
（3）with_enc_and_ser，with_enc，with_ser的区别是什么，以及谁的性能更好？

**Comment by AmbitionXiang** [comment]
master是encryption mode; oblivious_soda是oblivious mode；其他的分支都是我们试验用的，可以不用管~

**Comment by SunnyXia3579** [comment]
好的，谢谢解答
