### ISSUE TITLE
Is the Implementation of Opaque Included in the Repo?

### ISSUE THREAD

**Issue by fantas1a** [tsinghua-ideal/flare#5]
Hello,

I wonder if the implementations of Opaque (e.g., its join, filter) described in the SODA VLDB'23 paper are included in this repo? I see there is a folder named op at the directory ./flare/snclave/src/, does the op here mean Opaque?

Thank you very much!

**Comment by fantas1a** [comment]
@AmbitionXiang

**Comment by AmbitionXiang** [comment]
The branch oblivious-opaque-* implemented it.

**Comment by fantas1a** [comment]
Thanks, I see. Then what is the difference between opaque_legacy_sgx and opaque_scalable_sgx? Thank you again!

**Comment by AmbitionXiang** [comment]
opaque_legacy_sgx can run on legacy SGX with minor performance overheads.
